package com.chanceman.menus;

import lombok.Getter;
import net.runelite.api.gameval.ItemID;

import java.util.HashSet;
import java.util.HashMap;

@Getter
public enum SkillItem
{

	BRONZE_AXE(ItemID.BRONZE_AXE, SkillOp.CHOP_DOWN),
	IRON_AXE(ItemID.IRON_AXE, SkillOp.CHOP_DOWN),
	STEEL_AXE(ItemID.STEEL_AXE, SkillOp.CHOP_DOWN),
	BLACK_AXE(ItemID.BLACK_AXE, SkillOp.CHOP_DOWN),
	MITHRIL_AXE(ItemID.MITHRIL_AXE, SkillOp.CHOP_DOWN),
	ADAMANT_AXE(ItemID.ADAMANT_AXE, SkillOp.CHOP_DOWN),
	RUNE_AXE(ItemID.RUNE_AXE, SkillOp.CHOP_DOWN),
	DRAGON_AXE(ItemID.DRAGON_AXE, SkillOp.CHOP_DOWN),
	CRYSTAL_AXE(ItemID.CRYSTAL_AXE, SkillOp.CHOP_DOWN),
	INFERNAL_AXE(ItemID.INFERNAL_AXE, SkillOp.CHOP_DOWN),
	GILDED_AXE(ItemID.TRAIL_GILDED_AXE, SkillOp.CHOP_DOWN),
	THIRD_AGE_AXE(ItemID._3A_AXE, SkillOp.CHOP_DOWN),

	BRONZE_FELLING_AXE(ItemID.BRONZE_AXE_2H, SkillOp.CHOP_DOWN),
	IRON_FELLING_AXE(ItemID.IRON_AXE_2H, SkillOp.CHOP_DOWN),
	STEEL_FELLING_AXE(ItemID.STEEL_AXE_2H, SkillOp.CHOP_DOWN),
	BLACK_FELLING_AXE(ItemID.BLACK_AXE_2H, SkillOp.CHOP_DOWN),
	MITHRIL_FELLING_AXE(ItemID.MITHRIL_AXE_2H, SkillOp.CHOP_DOWN),
	ADAMANT_FELLING_AXE(ItemID.ADAMANT_AXE_2H, SkillOp.CHOP_DOWN),
	RUNE_FELLING_AXE(ItemID.RUNE_AXE_2H, SkillOp.CHOP_DOWN),
	DRAGON_FELLING_AXE(ItemID.DRAGON_AXE_2H, SkillOp.CHOP_DOWN),
	CRYSTAL_FELLING_AXE(ItemID.CRYSTAL_AXE_2H, SkillOp.CHOP_DOWN),
	THIRD_AGE_FELLING_AXE(ItemID._3A_AXE_2H, SkillOp.CHOP_DOWN),

	BRONZE_PICKAXE(ItemID.BRONZE_PICKAXE, SkillOp.MINE),
	IRON_PICKAXE(ItemID.IRON_PICKAXE, SkillOp.MINE),
	STEEL_PICKAXE(ItemID.STEEL_PICKAXE, SkillOp.MINE),
	BLACK_PICKAXE(ItemID.BLACK_PICKAXE, SkillOp.MINE),
	MITHRIL_PICKAXE(ItemID.MITHRIL_PICKAXE, SkillOp.MINE),
	ADAMANT_PICKAXE(ItemID.ADAMANT_PICKAXE, SkillOp.MINE),
	RUNE_PICKAXE(ItemID.RUNE_PICKAXE, SkillOp.MINE),
	DRAGON_PICKAXE(ItemID.DRAGON_PICKAXE,SkillOp.MINE),
	CRYSTAL_PICKAXE(ItemID.CRYSTAL_PICKAXE,SkillOp.MINE),
	INFERNAL_PICKAXE(ItemID.INFERNAL_PICKAXE,SkillOp.MINE),
	GILDED_PICKAXE(ItemID.TRAIL_GILDED_PICKAXE, SkillOp.MINE),
	THIRD_AGE_PICKAXE(ItemID._3A_PICKAXE, SkillOp.MINE),

	SMALL_FISHING_NET(ItemID.NET, SkillOp.SMALL_NET),
	BIG_FISHING_NET(ItemID.BIG_NET, SkillOp.BIG_NET),
	LOBSTER_POT(ItemID.LOBSTER_POT, SkillOp.CAGE),
	FISHING_BAIT(ItemID.FISHING_BAIT, SkillOp.BAIT),
	FLY_FISHING_ROD(ItemID.FLY_FISHING_ROD, SkillOp.LURE),
	RAKE(ItemID.RAKE, SkillOp.RAKE),
	SHEARS(ItemID.SHEARS, SkillOp.SHEAR),
	SECATEURS(ItemID.SECATEURS, SkillOp.PRUNE),
	HARPOON(ItemID.HARPOON, SkillOp.HARPOON),
	BARB_TRAIL_HARPOON(ItemID.HUNTING_BARBED_HARPOON, SkillOp.HARPOON),
	DRAGON_HARPOON(ItemID.DRAGON_HARPOON, SkillOp.HARPOON),
	DRAGON_HARPOON_OR(ItemID.TRAILBLAZER_HARPOON_NO_INFERNAL, SkillOp.HARPOON),
	DRAGON_HARPOON_OR_TB(ItemID.TRAILBLAZER_RELOADED_HARPOON_NO_INFERNAL, SkillOp.HARPOON),
	INFERNAL_HARPOON(ItemID.INFERNAL_HARPOON, SkillOp.HARPOON),
	INFERNAL_HARPOON_UNCHARGED(ItemID.INFERNAL_HARPOON_EMPTY, SkillOp.HARPOON),
	INFERNAL_HARPOON_OR(ItemID.TRAILBLAZER_HARPOON, SkillOp.HARPOON),
	INFERNAL_HARPOON_OR_UNCHARGED(ItemID.TRAILBLAZER_HARPOON_EMPTY, SkillOp.HARPOON),
	CRYSTAL_HARPOON(ItemID.CRYSTAL_HARPOON , SkillOp.HARPOON),
	CRYSTAL_HARPOON_INACTIVE(ItemID.CRYSTAL_HARPOON_INACTIVE, SkillOp.HARPOON),
	FISH_OFFCUTS(ItemID.BRUT_FISH_CUTS, SkillOp.BAIT),
	FINE_FISH_OFFCUTS(ItemID.SAILING_FINE_FISH_OFFCUTS, SkillOp.BAIT),

	BRONZE_BAR(ItemID.BRONZE_BAR, SkillOp.SMITH),
	IRON_BAR(ItemID.IRON_BAR, SkillOp.SMITH),
	STEEL_BAR(ItemID.STEEL_BAR, SkillOp.SMITH),
	MITHRIL_BAR(ItemID.MITHRIL_BAR, SkillOp.SMITH),
	ADAMANTITE_BAR(ItemID.ADAMANTITE_BAR, SkillOp.SMITH),
	RUNITE_BAR(ItemID.RUNITE_BAR, SkillOp.SMITH),

	TIN_ORE(ItemID.TIN_ORE, SkillOp.SMELT),
	COPPER_ORE(ItemID.COPPER_ORE, SkillOp.SMELT),
	IRON_ORE(ItemID.IRON_ORE, SkillOp.SMELT),
	COAL(ItemID.COAL, SkillOp.SMELT),
	MITHRIL_ORE(ItemID.MITHRIL_ORE, SkillOp.SMELT),
	RUNITE_ORE(ItemID.RUNITE_ORE, SkillOp.SMELT),
	SILVER_ORE(ItemID.SILVER_ORE, SkillOp.SMELT),
	SILVER_BAR(ItemID.SILVER_BAR,SkillOp.SMELT),
	GOLD_ORE(ItemID.GOLD_ORE, SkillOp.SMELT),
	GOLD_BAR(ItemID.GOLD_BAR, SkillOp.SMELT),

	GRIMY_GUAM_LEAF(ItemID.UNIDENTIFIED_GUAM, SkillOp.CLEAN),
	GRIMY_MARRENTILL(ItemID.UNIDENTIFIED_MARENTILL, SkillOp.CLEAN),
	GRIMY_TARROMIN(ItemID.UNIDENTIFIED_TARROMIN, SkillOp.CLEAN),
	GRIMY_HARRALANDER(ItemID.UNIDENTIFIED_HARRALANDER, SkillOp.CLEAN),
	GRIMY_RANARR_WEED(ItemID.UNIDENTIFIED_RANARR, SkillOp.CLEAN),
	GRIMY_IRIT_LEAF(ItemID.UNIDENTIFIED_IRIT, SkillOp.CLEAN),
	GRIMY_AVANTOE(ItemID.UNIDENTIFIED_AVANTOE, SkillOp.CLEAN),
	GRIMY_KWUARM(ItemID.UNIDENTIFIED_KWUARM, SkillOp.CLEAN),
	GRIMY_CADANTINE(ItemID.UNIDENTIFIED_CADANTINE, SkillOp.CLEAN),
	GRIMY_DWARF_WEED(ItemID.UNIDENTIFIED_DWARF_WEED, SkillOp.CLEAN),
	GRIMY_TORSTOL(ItemID.UNIDENTIFIED_TORSTOL, SkillOp.CLEAN),
	GRIMY_LANTADYME(ItemID.UNIDENTIFIED_LANTADYME, SkillOp.CLEAN),
	GRIMY_TOADFLAX(ItemID.UNIDENTIFIED_TOADFLAX, SkillOp.CLEAN),
	GRIMY_SNAPDRAGON(ItemID.UNIDENTIFIED_SNAPDRAGON, SkillOp.CLEAN),

	UNFIRED_BOWL(ItemID.BOWL_UNFIRED, SkillOp.FIRE),
	UNFIRED_CUP(ItemID.CUP_UNFIRED , SkillOp.FIRE),
	UNFIRED_PIE_DISH(ItemID.PIEDISH_UNFIRED, SkillOp.FIRE),
	UNFIRED_PLANT_POT(ItemID.PLANTPOT_UNFIRED, SkillOp.FIRE),
	UNFIRED_POT(ItemID.POT_UNFIRED, SkillOp.FIRE),
	UNFIRED_POT_LID(ItemID.POTLID_UNFIRED, SkillOp.FIRE),

	RUNE_ESSENCE(ItemID.BLANKRUNE, SkillOp.CRAFT_RUNE),
	PURE_ESSENCE(ItemID.BLANKRUNE_HIGH, SkillOp.CRAFT_RUNE),
	GUARDIAN_ESSENCE(ItemID.GOTR_GUARDIAN_ESSENCE, SkillOp.CRAFT_RUNE, false),

	//Blackjacks
	OAK_BLACKJACK_O(ItemID.ROGUETRADER_BJ_ASSAULT_OAK, SkillOp.LURE),
	OAK_BLACKJACK_D(ItemID.ROGUETRADER_BJ_DEFEND_OAK, SkillOp.LURE),
	WILLOW_BLACKJACK(ItemID.BLACKJACK_WILLOW, SkillOp.LURE),
	WILLOW_BLACKJACK_O(ItemID.ROGUETRADER_BJ_ASSAULT_WILLOW, SkillOp.LURE),
	WILLOW_BLACKJACK_D(ItemID.ROGUETRADER_BJ_DEFEND_WILLOW , SkillOp.LURE),
	MAPLE_BLACKJACK(ItemID.ROGUETRADER_BJ_MAPLE, SkillOp.LURE),
	MAPLE_BLACKJACK_O(ItemID.ROGUETRADER_BJ_ASSAULT_MAPLE, SkillOp.LURE),
	MAPLE_BLACKJACK_D(ItemID.ROGUETRADER_BJ_DEFEND_MAPLE, SkillOp.LURE),

	// Untradeables that conflict
	OAK_BLACKJACK(ItemID.BLACKJACK_OAK, SkillOp.LURE, false),
	RED_VINE_WORMS(ItemID.RED_VINE_WORM, SkillOp.BAIT, false),
	ELEMENTAL_METAL(ItemID.ELEMENTAL_WORKSHOP_BAR, SkillOp.SMITH, false),
	PRIMED_MIND_BAR(ItemID.ELEM_MIND_BAR, SkillOp.SMITH, false),
	BOBS_NET(ItemID.EVIL_BOB_NET, SkillOp.SMALL_NET, false);

	private final int id;
	private final SkillOp option;
	private final boolean requiresUnlock;

	SkillItem(int id, SkillOp option)
	{
		this(id, option, true);
	}

	SkillItem(int id, SkillOp option, boolean requiresUnlock)
	{
		this.id = id;
		this.option = option;
		this.requiresUnlock = requiresUnlock;
	}

	public SkillOp getSkillOp()
	{
		return option;
	}

	private static final HashSet<Integer> ALL_SKILL_ITEMS = new HashSet<>();
	private static final HashMap<Integer, SkillItem> ID_TO_ITEM = new HashMap<>();

	static
	{
		for (SkillItem skillItem : SkillItem.values())
		{
			ALL_SKILL_ITEMS.add(skillItem.getId());
			ID_TO_ITEM.put(skillItem.getId(), skillItem);
		}
	}

	public static boolean isSkillItem(int id)
	{
		return ALL_SKILL_ITEMS.contains(id);
	}

	public static SkillItem fromId(int id)
	{
		return ID_TO_ITEM.get(id);
	}
}
